config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :reports
    end
  end

  scope "(:locale)", locale: /en|fr/ do
    resources :awards
    resources :teams, only: [:index, :show]
    resources :reports, only: [:index, :show] do
      resources :report_awards
    end

    get 'thanks', to: 'reports#thanks'

    get "/map" => "reports#index"

    namespace :moderation do

      get 'signup', to: 'moderators#new', as: 'signup'
      get 'login', to: 'sessions#new', as: 'login'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      get 'dashboard', to: 'dashboard#show', as: 'dashboard'
      resources :game_states, only: [:index]
      resources :moderators
      resources :report_awards
      resources :reports
      resources :sessions

      get '/' => "locales#index"
    end
  end

  get "git_sha" => "diagnostics#git_sha"
  get "env" => "diagnostics#env"

  namespace :admin do
    resources :trello_cards, only: [:index]
  end

  get '/docs/d12-en-v7.little.pdf', :to => redirect('/docs/d12.en.pdf')
  get '/docs/d12-fr-v7.petit.pdf', :to => redirect('/docs/d12.fr.pdf')

  root to: 'locales#index'

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path

end

app/models/award.rb
class Award < ActiveRecord::Base
  has_many :report_awards, dependent: :destroy, inverse_of: :award
  has_many :reports, through: :report_awards
  has_many :trophies

  scope :with_approved_reports, -> { joins(:reports).group('awards.id').having('count(reports.id) > 0').where("reports.moderation_outcome = 'approved'") }

  def name
    I18n.t("cg.awards.award_#{id}")
  end

  def description
    I18n.t("cg.awards.award_#{id}_description")
  end

  def winners
    trophies.where(rank: "winner").map(&:team)
  end

  def runner_ups
    trophies.where(rank: "runner_up").map(&:team)
  end

  def mentions
    trophies.where(rank: "mention").map(&:team)
  end
end

app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  def index
    @awards = Award.all.includes :reports
  end
end

app/views/awards/_award.html.erb
<% if award.reports.try(:any?) %>
  <h1 class="award-title award-title-<%= index %>"><%= award.name %></h1>
  <p class="margin-top-20"><%= award.description %></p>

  <div class="scroll-horizontal awards">
    <div class="no-line-breaks width-auto">
      <% award.trophies.order_by_rank.each do |trophy| %>
        <%= render(partial: "trophy", locals: { trophy: trophy }) %>
      <% end %>
      <% for report in award.reports.with_pictures.order(id: :desc) %>
        <div class="inline-block text-center award">
          <%= link_to image_tag(report.primary_picture_url(:small), class: 'image'), report_path(I18n.locale, report.id), target: '_blank' %>

          <p class="line-breaks">
            <strong>
              <%= link_to report.title, report_path(I18n.locale, report), target: '_blank' %>
            </strong>

            <% if report.team %>
              <br /><em><%= t('cg.copy.awards.by') %></em>
              <br/><%= link_to report.team.name, team_path(I18n.locale, report.team), target: '_blank' %>
            <% end %>
          </p>

          <% unless games_ended? %>
            <p>
              <%= link_to t('cg.awards.nominate'), report_report_award_path(report_id: report.id, id: award.id, locale: I18n.locale), class: 'btn btn-magenta nominate' %>
            </p>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="diagonal-line-container clearfix">
    <% odd_or_even = index % 2 == 0 ? 'even' : 'odd' %>
    <div class="diagonal-line <%= odd_or_even %>"></div>
  </div>
<% end %>

app/views/awards/_trophy.html.erb
<%

team = trophy.team
raise("Trophy #{trophy.id} does not have a team") unless team

%>

<div class="inline-block text-center award trophy trophy-rank-<%= trophy.rank %>">
  <p><%= t('cg.awards.trophies.' + trophy.rank) %></p>
  <%= link_to image_tag(trophy.picture_url(:small), class: 'image'), team_path(I18n.locale, team.id), target: '_blank' %>

  <p class="line-breaks">
    <strong>
      <%= link_to team.name, team_path(I18n.locale, team), target: '_blank' %>
    </strong>
  </p>
</div>

app/views/awards/index.html.erb
<div class="modal fade" id="wrapup-modal">
  <div class="modal-dialog">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <h4 class="modal-title">&nbsp;</h4>
    </div>
    <div class="modal-content">
      <div class="modal-body text-center">
        <div class="embed-responsive embed-responsive-16by9" id="wrapup-player">
        </div>
      </div>
    </div>
  </div>
</div>

<div class="slide parallax-window" data-parallax="scroll" data-image-src="<%= image_path('show/jellyfish.jpg') %>">
  <div class="row">
    <div class="col-xs-10 col-xs-offset-1">
      <h1><%= t "cg.menu.awards" %></h1>
    </div>
  </div>

  <div class="row">
    <div class="col-xs-11 col-xs-offset-1">
      <ul class="list-inline">
        <li class="button-icon" id="play-wrapup-video">
          <a href="#" id="launch-wrapup-video"><%= t "cg.copy.home.play_wrapup_video" %></a></li>
      </ul>
    </div>
  </div>
</div>

<div class="row content padding-top-0 padding-bottom-0">
  <div class="col-xs-10 col-xs-offset-1 col-md-8 col-md-offset-1">
    <%= t('cg.copy.awards.introduction').html_safe %>
  </div>
</div>

<div class="row content padding-top-15">
  <div class="col-xs-10 col-xs-offset-1 col-md-11 col-md-offset-1">
    <div class="diagonal-line-container clearfix">
      <div class="diagonal-line even"></div>
    </div>

    <% if @awards.try(:any?) %>
      <ul class="list-unstyled">
        <% @awards.each_with_index do |award, index| %>
          <li><%= render partial: 'awards/award', locals: { award: award, index: index + 1 }  %></li>
        <% end %>
      </ul>
    <% else %>
      <p><%= t('cg.awards.no_awards_found') %></p>
    <% end %>
  </div>

  <div class="col-xs-10 col-xs-offset-1 col-md-11 col-md-offset-1">
  <h2 class="title-redlines text-center">
    <a href="http://d12.paris/" target="_blank"><strong><%= t('cg.copy.awards.redlines_are_not') %></strong></a><br />
    #redlines #d12
  </h2>
  </div>

</div>