config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :reports
    end
  end

  scope "(:locale)", locale: /en|fr/ do
    resources :awards
    resources :teams, only: [:index, :show]
    resources :reports, only: [:index, :show] do
      resources :report_awards
    end

    get 'thanks', to: 'reports#thanks'

    get "/map" => "reports#index"

    namespace :moderation do

      get 'signup', to: 'moderators#new', as: 'signup'
      get 'login', to: 'sessions#new', as: 'login'
      get 'logout', to: 'sessions#destroy', as: 'logout'
      get 'dashboard', to: 'dashboard#show', as: 'dashboard'
      resources :game_states, only: [:index]
      resources :moderators
      resources :report_awards
      resources :reports
      resources :sessions

      get '/' => "locales#index"
    end
  end

  get "git_sha" => "diagnostics#git_sha"
  get "env" => "diagnostics#env"

  namespace :admin do
    resources :trello_cards, only: [:index]
  end

  get '/docs/d12-en-v7.little.pdf', :to => redirect('/docs/d12.en.pdf')
  get '/docs/d12-fr-v7.petit.pdf', :to => redirect('/docs/d12.fr.pdf')

  root to: 'locales#index'

  mount Refinery::Core::Engine, at: Refinery::Core.mounted_path

end

app/models/report.rb
class Report < ActiveRecord::Base
  CATEGORIES = [[I18n.t('cg.reports.adventure'), 'adventure'], [I18n.t('cg.reports.intel'), 'intel']]

  attr_accessor :password
  has_many :links
  belongs_to :team
  belongs_to :current_moderator, class_name: "Moderator"
  belongs_to :game_round

  has_many :report_awards, dependent: :destroy, inverse_of: :report
  has_many :awards, through: :report_awards

  after_initialize :defaults
  before_validation { image.clear if @delete_image }

  has_attached_file :image, styles: { large: '1024x1024>', small: '150x150>', thumb: '60x60#', original: '100%' }, convert_options: { all: '-strip' }, default_style: :large, default_url: 'https://www.climategames.net/assets/small/missing.png'
  validates_attachment_content_type :image, content_type: ['image/jpg', 'image/jpeg', 'image/png', 'image/gif']

  has_many :pictures, as: :picturable, dependent: :destroy
  accepts_nested_attributes_for :pictures

  validates :title, :latitude, :longitude, :date_time, presence: true
  validates :location, presence: true, unless: Proc.new { |r| r.longitude.present? && r.latitude.present? }
  validates :password, presence: true, unless: Proc.new { |r| r.team_id.blank? }, on: :create
  validates :game_round, presence: true

  validate :authenticate_team_if_present, on: :create
  validate :check_location_has_a_lat_lng

  validate :check_moderation_outcome_valid

  accepts_nested_attributes_for :links, reject_if: :all_blank, allow_destroy: true
  accepts_nested_attributes_for :awards, reject_if: :all_blank, allow_destroy: true

  scope :with_award, -> (award_id) { joins(:awards).group('reports.id').having('count(awards.id) > 0').where('awards.id = ?', award_id) }
  scope :with_pictures, -> { joins(:pictures).group('reports.id').having('count(pictures.id) > 0') }
  scope :with_team, -> (team_id) { where('team_id = ?', team_id) }

  scope :approved, -> { where(moderation_outcome: 'approved') }
  scope :rejected, -> { where(moderation_outcome: 'rejected') }
  scope :pending, -> { where("moderation_outcome is NULL OR moderation_outcome = '' OR moderation_outcome = 'pending'") }

  scope :adventure, -> { where(category: 'adventure') }
  scope :intel, -> { where(category: 'intel') }

  def destroy_pictures_with_id(delete_ids)
    if delete_ids.try(:any?)
      pictures_to_delete = self.pictures.where id: delete_ids
      pictures_to_delete.each { |picture| picture.destroy }
    end
  end

  def primary_picture_url(style = nil)
    if self.pictures.any?
      pictures.first.image style.try(:to_sym)
    else
      ActionController::Base.helpers.asset_path("pictures/missing_#{I18n.locale.to_s}.png")
    end
  end

  def delete_image
    @delete_image ||= false
  end

  def delete_image=(value)
    @delete_image = !value.to_i.zero?
  end

  def rejected?
    moderation_outcome == "rejected"
  end

  def approved?
    moderation_outcome == "approved"
  end

  def pending?
    moderation_outcome.blank?
  end

  def self.moderation_outcome_options
    %w{approved pending rejected}
  end

  def self.category_options
    %w{intel adventure}
  end

  def update_from_moderation!(params)
    update_attributes!(params.merge(current_moderator: nil, checked_at: Time.current))
  end

  def tweet_text
    # We have 140 characters. https link takes up 24 characters with t.co shortening + space before.
    #  #ClimateGames prefixed by a space is another 14 characters.
    #  via @Climate_Games prefixed by a space is another 19 characters.
    # So we have 83 characters left
    text = ""
    characters_left = 83
    if team
      characters_left = characters_left - team.name.length - 4
    end

    if team && characters_left > 50
      text = "#{title.truncate(characters_left)} by #{team.name}"
    else
      text = title.truncate(83)
    end
    return CGI.escape(text)
  end

  def check_location_has_a_lat_lng
    if location && !latitude || !longitude
      errors.add :location, I18n.t('cg.reports.is_invalid')
    end
  end

  def check_moderation_outcome_valid
    return if moderation_outcome.blank?
    return if Report::moderation_outcome_options.include? moderation_outcome
    errors.add :moderation_outcome, I18n.t('cg.reports.invalid_moderation_outcome')
  end

  def authenticate_team_if_present
    return unless team_id

    team = Team.find_by_id team_id
    authenticated = team.authenticate password if team

    if !team || !authenticated
      errors.add :password, I18n.t('cg.reports.is_incorrect')
    end
  end

  private

  def defaults
    self.game_round = GameRound.current
  end
end

app/controllers/api/v1/reports_controller.rb
class Api::V1::ReportsController < Api::V1::ApplicationController
  def index
    @reports = Report.includes(:pictures).approved.order id: :desc

    if params[:category]
      allowed_categories = Report::CATEGORIES.map { |category| category[1] }
      head :bad_request and return unless allowed_categories.include? params[:category]
      @reports = @reports.where category: params[:category]
    end

    if params[:team_id]
      team = Team.find params[:team_id]
      @reports = @reports.with_team team.id
    end

    if params[:award_id]
      award = Award.find params[:award_id]
      @reports = @reports.with_award award.id
    end

    if @reports.any?
      @teams = Team.where id: @reports.map(&:team_id).uniq!
    else
      @teams = []
    end
  end
end

app/controllers/moderation/reports_controller.rb
class Moderation::ReportsController < Moderation::ModerationController
  def index
    @reports = Report.includes(:team).order("id DESC").all
    if @outcome = params[:outcome]
      available_outcomes = %w{approved rejected pending}
      if available_outcomes.include? @outcome
        @reports = @reports.send(@outcome)
      else
        flash[:alert] = I18n::t("moderation.invalid_outcome", outcome: @outcome)
      end
    end
  end

  def edit
    @report = Report.find(params[:id])
    if @report.current_moderator && @report.current_moderator != current_moderator
      if current_moderator.super_cape?
        flash[:alert] = I18n::t("moderation.current_moderator_alert", username: @report.current_moderator.username)
      else
        redirect_to moderation_reports_path(locale: locale.to_s), alert: I18n::t("moderation.current_moderator_alert", username: @report.current_moderator.username)
        return
      end
    else
      @report.update_attributes(current_moderator: current_moderator)
    end
    @report.moderation_outcome = "pending" if @report.pending?
    @teams = Team.all.order('lower(name)')
  end

  def update
    @report = Report.find(params[:id])
    @report.update_from_moderation!(report_attrs)
    @report.destroy_pictures_with_id params[:image_ids_to_delete]
    redirect_to moderation_reports_path(outcome: "pending", locale: locale.to_s), notice: I18n::t("moderation.successfully_updated_report")
  end

  private

  def report_attrs
    params.
      require(:report).
      permit(:title,
             :team_id,
             :moderation_outcome,
             :internal_memo,
             :description,
             :date_time,
             :awards,
             :image,
             :category,
             :latitude,
             :longitude,
             :location,
             :delete_image,
             award_ids: [],
             links_attributes: [:id, :url, :_destroy],
             pictures_attributes: [:id, :image, :_destroy],
             )
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  include ActionView::Helpers::TextHelper

  skip_before_filter :verify_authenticity_token
  before_filter :suspend_when_applicable
  before_filter :render_maintenance_when_enabled, except: [:index, :show]
  before_filter :redirect_when_games_ended, except: [:index, :show]

  def index
    @reports = Report.approved.order('id DESC')
    @teams = Team.with_approved_reports.alphabetical
    @awards = Award.with_approved_reports
    @body_class = "map"
  end

  def show
    @report = Report.approved.find params[:id]
  end

  def new
    @report = Report.new category: Report::CATEGORIES[0][1], date_time: Time.now
  end

  def create
    @report = Report.new report_attrs
    if @report.save
      redirect_to "/#{params[:locale]}#{thanks_path}"
    else
      render :new
    end
  end

  private

  def suspend_when_applicable
    if ENV['suspend_game_map'] == "1"
      @reports = []
      render :suspended
    end
  end

  def render_maintenance_when_enabled
    if ENV['enable_maintenance'].to_i == 1
      render text: I18n.t('cg.copy.reports.maintenance'), status: :service_unavailable
    end
  end

  def redirect_when_games_ended
    if view_context.games_ended?
      redirect_to "/#{params[:locale]}/games-ended"
    end
  end

  def report_attrs
    params.
      require(:report).
      permit(:category,
             :title,
             :date_time,
             :location,
             :latitude,
             :longitude,
             :image,
             :description,
             :team_id,
             :password,
             award_ids: [],
             pictures_attributes: [:id, :image, :_destroy],
             links_attributes: [:id, :url, :_destroy])
  end
end

app/views/reports/_form.html.erb
<%= f.error_notification %>

<% if !try(:current_moderator) %>
  <p>
    <%= t('cg.reports.if_no_team_message.start') %>
    <%= link_to t('cg.reports.if_no_team_message.action'), new_team_path(locale: I18n.locale) %>
    <%= t('cg.reports.if_no_team_message.end') %>
  </p>
<% end %>

<%= f.input :category, collection: Report::CATEGORIES, as: :radio_buttons, label: false  %>
<%= f.input :title, label: t('cg.reports.title'), placeholder: t('cg.reports.title') %>
<div class="location-container">
  <label><%= t('cg.reports.location') %></label>
  <div class="input-group location-group">
    <%= f.input :location, label: false, placeholder: t('cg.reports.search_for_place') %>
    <span class="input-group-addon">
        <i class="glyphicon glyphicon-search"></i>
    </span>
  </div>
  <div class="form-group">
    <div id="map" class="new"></div>
  </div>
</div>
<%= f.input :latitude, as: :hidden %>
<%= f.input :longitude, as: :hidden %>

<%= f.input :description, input_html: { rows: 6 }, label: t('cg.reports.description'), placeholder: t('cg.reports.description_placeholder') %>

<% if try(:current_moderator) %>
  <%= f.association :team, collection: @teams, prompt: t('cg.reports.no_team'), label: t('activerecord.attributes.report.team') %>
  <%= f.association :awards, as: :check_boxes, label: false %>
<% else %>
  <label><%= t('cg.reports.select_a_team') %> <small><%= t('cg.reports.optional') %></small></label>
  <% if !@report.team_id && !@report.award_ids.any? %>
    <div id="claim-team-points" class="form-group">
      <%= link_to "+ #{t('cg.reports.attach_to_a_team')}", '#', class: 'btn btn-default' %>
    </div>
  <% end %>

  <div id="claim-fields" <%= ' class="show"'.html_safe if @report.team_id || @report.award_ids.any? %>>
    <%= f.association :team, collection: Team.alphabetical, prompt: t('cg.reports.no_team'), label: false %>
    <%= f.input :password, label: t('cg.reports.password') %>

    <label><%= t('cg.reports.awards') %> <small><%= t('cg.reports.optional') %></small></label>
    <br/>
    <small class="margin-bottom-15">
      <%= t('cg.reports.please_select_the_awards') %>
    </small>

    <%= f.association :awards, as: :check_boxes, :label => false, :label_method => lambda { |award| "#{award.name} <abbr rel='tooltip' title='#{award.name}: #{award.description}'><i class='fa fa-question'></i></abbr>".html_safe } %>
  </div>
<% end %>

<label><%= t('cg.reports.pictures') %> <small><%= t('cg.reports.optional') %></small></label>
<div id="pictures" class="form-group">
  <%= f.simple_fields_for :pictures do |picture| %>
    <%= render 'reports/picture_fields', :f => picture %>
  <% end %>
  <div class="pictures">
    <%= link_to_add_association "+ #{t('cg.reports.add_picture')}", f, :pictures, partial: 'reports/picture_fields', class: 'btn btn-default' %>
  </div>
</div>

<label><%= t('cg.reports.links') %> <small><%= t('cg.reports.optional') %></small></label>
<div id="links" class="form-group">
  <%= f.simple_fields_for :links do |link| %>
    <%= render 'reports/link_fields', :f => link %>
  <% end %>
  <div class="links">
    <%= link_to_add_association "+ #{t('cg.reports.add_link')}", f, :links, class: 'btn btn-default' %>
  </div>
</div>

<%= f.input :date_time, label: t('cg.reports.date_time') %>

<% if try(:current_moderator) %>
  <%= f.input :moderation_outcome, label: t("activerecord.attributes.report.moderation_outcome"), as: :radio_buttons, collection: Report.moderation_outcome_options %>
  <%= f.input :internal_memo, input_html: { rows: 4 }, label: t("activerecord.attributes.report.internal_memo")  %>
<% else %>
  <p class="margin-top-15">
    <%= t('cg.reports.dont_despair') %>
  </p>
<% end %>

<div class="margin-top-20 margin-bottom-20">
  <%= f.button :submit, t('cg.reports.submit_report'), class: 'btn btn-magenta btn-send-report' %>
</div>

app/views/reports/_link_fields.html.erb
<div class="nested-fields">
  <%= f.input :url, label: t('cg.reports.url') %>

  <div class="text-right">
    <small><%= link_to_remove_association t('cg.reports.remove'), f %></small>
  </div>
</div>

app/views/reports/_picture_fields.html.erb
<% if f.object.try(:id) %>
  <p>
    <%= image_tag f.object.image(:small) %>
    <%= check_box_tag 'image_ids_to_delete[]', f.object.id, false, id: "image_id_to_delete_#{f.object.id}" %>
    <label class="optional control-label" for="image_id_to_delete_<%= f.object.id %>"><%= t("moderation.report.delete_image") %></label>
    <p><%= link_to t('cg.pictures.link_to_original'), f.object.image(:original), target: '_blank' %></p>
  </p>

<% else %>
  <div class="nested-fields">
    <%= f.input :image, as: :file, label: false %>

    <div class="text-right">
      <small><%= link_to_remove_association t('cg.reports.remove'), f %></small>
    </div>
  </div>
<% end %>

app/views/reports/index.html.erb
<div id="map" class="index" data-more-link-text="<%= t('cg.reports.more_info') %>"></div>
<div class="relative">
  <div class="row content side-padding">
    <div class="col-xs-12">
      <ul class="nav nav-tabs" role="tablist" id="tabs">
        <li role="presentation"><a href="#" data-toggle="modal" data-target="#about" id="about_button"></a></li>
        <li role="presentation" class="active"><a href="#map-tab" role="tab" data-toggle="tab"><%= t('cg.reports.map') %></a></li>
        <li role="presentation"><a href="#list-tab" role="tab" data-toggle="tab"><%= t('cg.reports.list') %></a></li>
      </ul>

      <div class="filters row margin-top-15">
        <div class="col-md-4">
          <div class="form-group">
            <select class="form-control" id="category_filter">
              <option value=""><%= t('cg.reports.all_reports') %></option>
              <% for category in Report::CATEGORIES %>
                <option value="<%= category[1] %>">
                  <%= category[0] %>
                </option>
              <% end %>
            </select>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <select class="form-control" id="team_filter">
              <option value=""><%= t('cg.reports.all_teams') %></option>
              <% if @teams && @teams.any? %>
                <% for team in @teams %>
                  <option value="<%= team.id %>">
                    <%= team.name %>
                  </option>
                <% end %>
              <% end %>
            </select>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <select class="form-control" id="award_filter">
              <option value=""><%= t('cg.reports.all_awards') %></option>
              <% if @awards && @awards.any? %>
                <% for award in @awards %>
                  <option value="<%= award.id %>">
                    <%= award.name %>
                  </option>
                <% end %>
              <% end %>
            </select>
          </div>
        </div>
      </div>

      <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="map-tab">
        </div>

        <div role="tabpanel" class="tab-pane fade" id="list-tab">
          <div class="row">
            <div class="col-md-12">
              <table class="table table-condensed table-striped">
                <thead class="hidden-xs">
                  <tr>
                    <th class="hidden-xs">&nbsp;</th>
                    <th><%= t('cg.reports.image') %></th>
                    <th><%= t('cg.reports.title') %></th>
                    <th class="hidden-xs"><%= t('cg.reports.team') %></th>
                    <th><%= t('cg.reports.date_time') %></th>
                    <th class="hidden-xs"><%= t('cg.reports.location') %></th>
                    <th>&nbsp;</th>
                  </tr>
                </thead>
                <tbody id="reports-list">
                </tbody>
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="about">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title"><%= t('cg.reports.about') %></h4>
      </div>

      <div class="modal-body">
        <%= t('cg.reports.map_intro').html_safe %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('cg.reports.close') %></button>
      </div>
    </div>
  </div>
</div>

app/views/reports/new.html.erb
<div class="row content side-padding">
  <div class="side-padding">
    <h1><a class="mobile-only" href="<%= reports_path(locale: I18n.locale) %>"><i class="glyphicon glyphicon-chevron-left"></i></a> <%= t('cg.reports.new_report') %></h1>

    <%= simple_form_for @report, url: reports_path(locale: I18n.locale) do |f| %>
      <%= render partial: 'reports/form', locals: { f: f } %>
    <% end %>
  </div>
</div>

app/views/reports/show.html.erb
<% content_for :title do %>
  <%= @report.title %>
<% end %>

<% content_for :meta do %>

  <%
  if @report.description && @report.description.present?
    meta_description = @report.description
  elsif @report.team
    meta_description = "#{t('cg.meta.description.a_report_from')} #{@report.team.name}"
  else
    meta_description = ""
  end
  %>

  <meta name="description" content="<%= meta_description %>" />
  <meta property="og:description" content="<%= meta_description %>" />

  <% if @report.pictures.any? %>
    <meta property="og:image" content="<%= "#{request.protocol}#{request.host_with_port}#{@report.primary_picture_url(:original)}" %>" />
  <% elsif @report.team && @report.team.image_file_name %>
    <meta property="og:image" content="<%= "#{request.protocol}#{request.host_with_port}#{@report.team.image.url(:original)}" %>" />
  <% end %>

<% end %>

<div class="row content">
  <div class="col-xs-10 col-xs-offset-1">
    <div class="row">
      <div class="col-sm-4 no-side-padding" style="background: #f1f1f1;">
        <%= link_to(image_tag(@report.primary_picture_url(:large), class: 'img-responsive avatar'), @report.primary_picture_url(:original)) %>

        <% picture_count = @report.pictures.length %>
        <% if picture_count > 1 %>
          <% for picture in @report.pictures[1..picture_count] %>
            <%= link_to(image_tag(picture.image.url(:large), class: 'img-responsive avatar'), picture.image.url(:original)) %>
          <% end %>
        <% end %>
      </div>

      <div class="col-sm-8">
        <h1 class="margin-top-0"><%= @report.title %></h1>
        <div>
          <small><%= t("cg.reports.#{@report.category}") %> <%= t('cg.reports.at_time') %> <%= "#{l(@report.date_time, format: '%A %e %b %Y')} #{t('cg.reports.at_about')} #{l(@report.date_time, format:'%l%P')}" %></small>
        </div>

        <div class="social-media-sharing padding-top-bottom">
          <a href="https://twitter.com/intent/tweet?text=<%= @report.tweet_text %>&url=<%= report_url(:locale => I18n.locale.to_s, :id => @report.id) %>&hashtags=ClimateGames&via=Climate_Games&related=Climate_Games,HackCOP21"
            class="btn btn-large share-button twitter-share-button" target="_blank"><span class="fa fa-twitter"></span> Tweet</a>
          <a href="http://www.facebook.com/sharer.php?u=<%= report_url(:locale => I18n.locale.to_s, :id => @report.id) %>"
            class="btn btn-large share-button facebook-share-button" target="_blank"><span class="fa fa-facebook-official"></span> Share on Facebook</a>
        </div>

        <div class="row margin-top-5">
          <div class="col-xs-12">
            <%= simple_format @report.description %>

            <% if @report && @report.links.any? %>
              <h4><%= t('cg.reports.links') %></h4>
              <ul class="margin-top-0">
                <% for report_link in @report.links %>
                  <li><%= link_to report_link.url, url_with_protocol(report_link.url), target: "_blank" %></li>
                <% end %>
              </ul>
            <% end %>
          </div>
        </div>

        <input id="report_latitude" value="<%= @report.latitude %>" disabled class="hidden" />
        <input id="report_longitude" value="<%= @report.longitude %>" disabled class="hidden" />

        <h4><%= t('cg.reports.map') %></h4>
        <div id="map" class="show"></div>
        <a target="_blank" href="<%= "https://www.openstreetmap.org/?mlat=#{@report.latitude}&mlon=#{@report.longitude}#map=16/#{@report.latitude}/#{@report.longitude}" %>"><%= t('cg.reports.view_larger_map') %></a>


      </div>
    </div>

    <% if @report && @report.report_awards.any? %>
      <div class="row margin-top-15">
        <div class="col-sm-8 col-sm-offset-4">
          <h4><%= t('cg.copy.teams.show.nominated_for') %></h4>
        </div>
      </div>

      <% for report_award in @report.report_awards %>
      <div class="row margin-top-5">
        <div class="col-sm-8 col-sm-offset-4">
          <div class="row padding-top-bottom" style="background: #f1f1f1;">
            <div class="col-xs-8 padding-top-bottom-10">
              <strong><%= report_award.award.name %> <abbr class='hidden-xs' rel='tooltip' title='<%= "#{report_award.award.name}: #{report_award.award.description} "%>'><i class='fa fa-question'></i></abbr></strong>
              <span class="visible-xs-inline">
                <br/><small><%= report_award.award.description %></small>
              </span>
            </div>
            <% unless games_ended? %>
              <div class="col-xs-4" style="text-align:right;">
                <%= link_to t('cg.awards.nominate'), report_report_award_path(report_id: report_award.report.id, id: report_award.award.id, locale: I18n.locale), class: 'btn btn-magenta nominate' %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    <% end %>

    <% if @report.team %>
    <div class="row margin-top-15">
        <% team_link = "/#{::I18n.locale}/teams/#{@report.team.id}" %>

        <div class="col-xs-4" style="background: #f1f1f1;">
          <%= link_to image_tag(@report.team.image.url(:small), class: 'img-responsive avatar'), team_link %>
        </div>

        <div class="col-xs-8">
          <h4 class="margin-top-0">
            <%= link_to("Team: #{@report.team.name}", team_link) %>
          </h4>

          <% if @report.team.nature %>
            <p>
              <%= truncate(@report.team.nature, length: 200) %>
              <% if @report.team.approved_reports.count > 1 %>
                <br/><%= link_to t('cg.reports.more_reports_from_this_team', count: @report.team.approved_reports.count-1), team_link %>
              <% end %>
            </p>
          <% end %>
        </div>
    </div>
    <% end %>

  </div>
</div>

app/views/reports/suspended.html.erb
<div class="relative">
  <div id="shrowd">
    <h1><%= t "cg.copy.reports.suspended.message" %></h1>
  </div>
  <div class="row content side-padding">
    <div class="col-xs-12">
      <ul class="nav nav-tabs" role="tablist">
        <li role="presentation"><a href="#" data-toggle="modal" data-target="#about" id="about_button"><%= t('cg.reports.about') %></a></li>
        <li role="presentation" class="active"><a href="#map-tab" role="tab" data-toggle="tab"><%= t('cg.reports.map') %></a></li>
        <li role="presentation"><a href="#list-tab" role="tab" data-toggle="tab"><%= t('cg.reports.list') %></a></li>
        <li class="pull-right" role="presentation"><%= link_to t('cg.reports.submit_report'), "/#{::I18n.locale}/reports/new", class: 'btn btn-magenta btn-submit-report no-right-margin' %></li>
      </ul>

      <div class="tab-content">
        <div role="tabpanel" class="tab-pane fade in active" id="map-tab">
          <div id="map" class="index" data-more-link-text="<%= t('cg.reports.more_info') %>"></div>
        </div>

        <div role="tabpanel" class="tab-pane fade" id="list-tab">
          <div class="row">
            <div class="col-md-12 margin-top-20">
              <div class="table-responsive">
                <table class="table table-condensed table-striped">
                  <thead>
                    <tr>
                      <th><%= t('cg.reports.image') %></th>
                      <th><%= t('cg.reports.team') %></th>
                      <th><%= t('cg.reports.title') %></th>
                      <th><%= t('cg.reports.location') %></th>
                      <th><%= t('cg.reports.longitude_latitude') %></th>
                    </tr>
                  </thead>
                  <tbody>
                    <% @reports.each do |report| %>
                      <tr>
                        <td>
                          <%= link_to image_tag(report.image(:thumb), class: 'img-circle thumb'), report.image.url, target: '_blank' %>
                        </td>
                        <td>
                          <% if report.team %>
                            <%= report.team.name %>
                          <% else %>
                            <%= t('cg.reports.none') %>
                          <% end %>
                        </td>
                        <td>
                          <%= report.title %>
                        </td>
                        <td>
                          <% if report.location.present? %>
                            <%= report.location %>
                          <% else %>
                            <%= t('cg.reports.none') %>
                          <% end %>
                        </td>
                        <td>
                          <% if report.longitude && report.latitude %>
                            <%= link_to "#{report.latitude}, #{report.longitude}", "https://www.openstreetmap.org/#map=19/#{report.latitude}/#{report.longitude}", target: '_blank' %>
                          <% else %>
                            <% t('cg.reports.none') %>
                          <% end %>
                        </td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="about">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title"><%= t('cg.reports.about') %></h4>
      </div>

      <div class="modal-body">
        <%= t('cg.reports.map_intro').html_safe %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t('cg.reports.close') %></button>
      </div>
    </div>
  </div>
</div>

app/views/reports/thanks.html.erb
<div class="row content side-padding">
  <div class="side-padding">
  	<h1><%= t('cg.reports.thanks') %></h1>

  	<%= t('cg.reports.thanks_moderation_message').html_safe %>

  	<p>
  		<a class="btn btn-magenta" href="<%= new_report_path(locale: I18n.locale) %>"><%= t('cg.reports.add_another_report') %></a>
  	</p>
  	<p>
		<a class="btn btn-green" href="<%= reports_path(locale: I18n.locale) %>"><%= t('cg.reports.back_to_the_map') %></a>
	</p>
  </p>
  </div>
</div>